### ISSUE TITLE
missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by lepardov2020** [nstrayer/datadrivencv#14]
Hi,
After trying to knit the HTML version I got this error

Quitting from lines 15-29 (cv.Rmd) 
 Error in if (!after) c(values, x) else if (after >= lengx) c(x, values) else c(x[1L:after],  : 
  missing value where TRUE/FALSE needed 

Any thoughts to get around this issue would be much appreciated!
cheers

PS. I have all cells of "in_resume" col filled with TRUE, no NA in column "section"

**Comment by nstrayer** [comment]
Do you have an entry that has both the start and end date missing?

**Comment by lepardov2020** [comment]
Yes, I had. Then I fixed the end dates to have at least one column with value. That did not work either, so I added start date to everything (however this does not make sense for a few things like short courses), but did not work either.  Any other suggestions?

**Comment by lepardov2020** [comment]
I found the issue! we have to convert the excel file in Drive into a google sheet itself! otherwise, it does not recognize the file apparently (even if public). I have now another issue but will post it in a different thread. Thanks

**Comment by hughcross** [comment]
Hello,

I hope someone can help. I am still getting the error:

```
Quitting from lines 15-29 (cv.rmd) 
 Error in if (!after) c(values, x) else if (after >= lengx) c(x, values) else c(x[1L:after],  : 
  missing value where TRUE/FALSE needed 
```

I have tried filling in everything in the csv (using both google sheets and local csvs) and still get the error.
